# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags

# SubNav
subnav:
  github: "https://github.com/kingwoshi"
  weibo: "http://weibo.com/meettheghost"
  rss: "/"
  # facebook: "/"
  # google: "/"
  # twitter: "/"
  # linkedin: "/"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous
baidu_analytics: true
favicon: /favicon.ico

#你的头像
avatar: "https://avatars0.githubusercontent.com/u/10783836?v=3&u=5e52d10d4f377f9a905a743e4cf43e4b747f8aae&s=140"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  金色洛菲尔: http://www.lolofinil.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: keep fit, keep code.
